---
- name: Install Apache
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: Start service
      service:
        name: httpd
        state: started
        enabled: true
